export const STARGAZERS_REQUEST = 'STARGAZERS_REQUEST';
export const STARGAZERS_FAILURE = 'STARGAZERS_FAILURE';
export const STARGAZERS_SUCCESS = 'STARGAZERS_SUCCESS';

export const STARRED_REQUEST = 'STARRED_REQUEST';
export const STARRED_FAILURE = 'STARRED_FAILURE';
export const STARRED_SUCCESS = 'STARRED_SUCCESS';

export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_FAILURE = 'USER_FAILURE'

export const REPO_REQUEST = 'REPO_REQUEST'
export const REPO_SUCCESS = 'REPO_SUCCESS'
export const REPO_FAILURE = 'REPO_FAILURE'

export const SEND_FORM_REQUEST = 'SEND_FORM_REQUEST'
export const SEND_FORM_SUCCESS = 'SEND_FORM_SUCCESS'
export const SEND_FORM_FAILURE = 'SEND_FORM_FAILURE'

export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'
export const SET_LANGUAGE = 'SET_LANGUAGE'
